### ISSUE TITLE
[feature] 能否加一些上下选择结果的快捷键？

### ISSUE THREAD

**Issue by 416207298** [lanyuanxiaoyao/Mverything#10]
1、选出的结果用上下箭头选择还是太麻烦了点，能否添加类似 vim 的快捷键用于选择？如：`ctrl + n` 等于下箭头、`ctrl + p`等于上箭头等；

2、能否在设置里加一个开关，用于控制是否需要按一下 `enter` 触发搜索，一般来说搜索的习惯是边输入边出结果，开始使用的很长时间我一直以为是这个插件不好使，后来发现是我没按 `enter`。。。

希望能添加以上两个功能。

**Comment by lanyuanxiaoyao** [comment]
> 1、选出的结果用上下箭头选择还是太麻烦了点，能否添加类似 vim 的快捷键用于选择？如：`ctrl + n` 等于下箭头、`ctrl + p`等于上箭头等；
> 
> 2、能否在设置里加一个开关，用于控制是否需要按一下 `enter` 触发搜索，一般来说搜索的习惯是边输入边出结果，开始使用的很长时间我一直以为是这个插件不好使，后来发现是我没按 `enter`。。。
> 
> 希望能添加以上两个功能。

uTools 插件市场有「Mverthing Plus」作为继任者，本插件就不继续更新了
