### ISSUE TITLE
Mac的Download文件夹下的文件无法被搜索

### ISSUE THREAD

**Issue by zhonghaojay** [lanyuanxiaoyao/Mverything#2]
Mac的Download文件夹和桌面文件夹下的文件无法被搜索

**Comment by lanyuanxiaoyao** [comment]
> Mac的Download文件夹和桌面文件夹下的文件无法被搜索

![](https://s2.ax1x.com/2020/03/05/3TdU1K.png)

我尝试了一下没问题, 你的系统版本是多少, 尝试用`mdfind`命令搜索一下看看能不能搜索到
