### ISSUE TITLE
MACOS 10.15.5版本，搜索到的文件，无法通过双击和右方向键打开了

### ISSUE THREAD

**Issue by qiquannan** [lanyuanxiaoyao/Mverything#4]
系统未升级之前挺好用的，升级后发现无法打开文件

**Comment by lanyuanxiaoyao** [comment]
> 系统未升级之前挺好用的，升级后发现无法打开文件

最近用得少, 没有发现这个问题, 这个是因为 utools 升级了相关 api, 我这里没有修改完整, 已修复, 等待插件中心审核
