### ISSUE TITLE
显示暂无数据

### ISSUE THREAD

**Issue by Symbolk** [lanyuanxiaoyao/Mverything#8]
你好，首先utools非常棒，这个插件也非常有用！正在逐步用utools代替Alfred。
但是，之前Alfred的文件搜索正常，这个插件好像无法正常使用，总是显示暂无数据，已试过重装插件、重启utools等。
系统：macOS 10.15.7
![Screen Shot 2021-01-24 at 10 34 07 AM](https://user-images.githubusercontent.com/14107297/105619672-fd3c6680-5e2f-11eb-94c2-d0396d324fb7.png)

**Comment by Symbolk** [comment]
哦我蠢了，原来要按回车，和Alfred直接显示的逻辑有点不同。。。

**Comment by lanyuanxiaoyao** [comment]
> 哦我蠢了，原来要按回车，和Alfred直接显示的逻辑有点不同。。。

Alfred 是他们自己对接 Spotlight 索引, 这个插件是在 Electron 基础上调用命令行实现的, 没有底层支持, 只能做到这个样子

**Comment by Symbolk** [comment]
> > 哦我蠢了，原来要按回车，和Alfred直接显示的逻辑有点不同。。。
> 
> Alfred 是他们自己对接 Spotlight 索引, 这个插件是在 Electron 基础上调用命令行实现的, 没有底层支持, 只能做到这个样子

嗯嗯，我也想到这一层了
